### PR TITLE
Using the cookie name that InfluxDB 2.1 returns instead of assuming "session"

### LINKED ISSUE #262: InfluxDB 2.1 Incompatibility with Session Cookie
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Use InfluxDB 2.1
2. Activate any API that uses the signin logic of ApiClient
3. Exception occurs due to a LINQ "Sequence contains no matching element"

Call stack:

> System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at InfluxDB.Client.Api.Client.ApiClient.InitToken()
   at InfluxDB.Client.Api.Client.ApiClient.BeforeIntercept(IRestRequest request)
   at InfluxDB.Client.Api.Client.ApiClient.InterceptRequest(IRestRequest request)
   at InfluxDB.Client.Api.Client.ApiClient.CallApiAsync(String path, Method method, List`1 queryParams, Object postBody, Dictionary`2 headerParams, Dictionary`2 formParams, Dictionary`2 fileParams, Dictionary`2 pathParams, String contentType, CancellationToken cancellationToken)

__Expected behavior:__
Not to throw exception

__Actual behavior:__
Exception thrown

The reason is that there is no longer a cookie called "session" for InfluxDB OSS. It is now called _influxdb-oss-session_.

__Specifications:__
 - Client Version: 3.2.0-dev
 - InfluxDB Version: 2.1 from Docker
 - Platform: Linux

### PR DESCRIPTION
**Pull request by sbhenderson**
Closes #262 

## Proposed Changes

Use the returned session cookie name instead of assuming "session". InfluxDB 2.1 has changed the name of the cookie; for OSS in particular, it returns _influxdb-oss-session_ instead.

Please discard the PR if it's not satisfactory, but this fix did work for me.

## Checklist

- [X] Rebased/mergeable
- [X] Commit messages are in [semantic format](https://seesparkbox.com/foundry/semantic_commit_messages)
- [X] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: Client/Internal/ApiClient.cs [hunk 1]
```diff
@@ -108,10 +110,17 @@ private void InitToken()
                     var cookies = authResponse.Cookies.ToList();
 
                     if (cookies.Count == 1)
-                        _sessionToken = cookies
-                            .First(cookie => cookie.Name.ToString().Equals("session"))
+                    {
```
Comment (sranka) [inline Client/Internal/ApiClient.cs:113]: Couldn't this be simplified to remember all cookies (or key/value pairs), which could be all later sent in the `Signout` method?

Comment (sbhenderson) [reply Client/Internal/ApiClient.cs:113]: That is very true, but I would also say that based on the code, it still seems that InfluxDB will only ever return 1 cookie; it's just that the name is not known at compile time anymore. 

So if you would prefer to open up that assumption and tolerate 1+ cookies sent, I can make the change and respond back.

Comment (bednar) [reply Client/Internal/ApiClient.cs:113]: @sranka simple and straightforward as usual 👍

Comment (bednar) [reply Client/Internal/ApiClient.cs:113]: @sbhenderson feel free to use @sranka's suggestion. It will be better for future maintenance.

**Review by bednar — CHANGES_REQUESTED** [review]
Thanks for your PR 👍.

There are a few requirements that must be be satisfy before we accept the PR:

File: Client/Internal/ApiClient.cs (hunk 1 above)
Comment (sbhenderson) [reply Client/Internal/ApiClient.cs]: I have made the change in line with @sranka's suggestion to store all names/values for using in future requests.

**Comment by sbhenderson** [comment]
@bednar @sranka I have completed the changed that was asked for. Can I request a re-review?

**Review by bednar — APPROVED** [review]
Thanks again for PR 👍 

LGTM
